version: 2
jobs:
  build:
     docker:
       - image: circleci/python:latest
     steps:
     - checkout # from github
     - run:
          command: |
            set -e
            mkdir results
            cp site/* results
     - store_artifacts:
         path: results
     - run: sudo pip install awscli --upgrade; whereis awscli; whereis aws
     - run:
          command: aws s3 sync site s3://nex4.tech --delete --acl public-read