version: 2
jobs:
  build:
     docker:
       - image: circleci/python:latest
     steps:
     - checkout # from github
     - run:
          command: |
            set -e
            mkdir results
            sudo pip install -r requirements.txt
            pip freeze > results/pythonpackages.txt
            grep "html-linter==0.4.0" results/pythonpackages.txt # to show how you could check versions
            bandit /usr/local/lib/python3.8/site-packages/html_linter.py -n 3 -ll
            python /usr/local/lib/python3.8/site-packages/html_linter.py --disable=optional_tag site/index.html # static website test
     - store_artifacts:
         path: results
     - run: sudo pip install awscli --upgrade; whereis awscli; whereis aws
     - run:
          name: Deploy to S3 if tests pass and branch is Master
          command: aws s3 sync site s3://demo2.d1g.nl --delete --acl public-read

# TODO exchange "demo2.d1g.nl" by the name of your S3 bucket!

# wget  "https://validator.w3.org/check?uri=https://websitedemo-pve-1.c9users.io/site/&output=json" -O validate.json
# grep error validate.json; test $? -eq 1
